---
:spring_version: current
:toc:
:project_id: desafio-rest-service
:spring_version: current
:spring_boot_version: 1.3.0.M4
:icons: font
:source-highlighter: prettify


== Descrição

Essa solução fornece os vencedores da categoria Pior Filme do Golden Raspberry Awards.

== Endpoins

Obtém os vencedores, informando um ano.
----
http://localhost:8080/movies/{year}
----

== Para Rodar o Aplicativo

----
1 - Na pasta do projeto no Packege Explorer, navege até o arquivo Application (src/main/java) na raiz do pacote com.desafioapp.app
2 - Clique com o botão direito em cima do arquivo Application.java-> Rum as-> Java Application
3 - O aplicativo iniciará e veja no console:

...
.........................................................
... LOAD DATA BEGIN ..................................
.........................................................
Path to CSV File C:\PROJETOS\JAVA\workspace\rest-service\target\classes\movielist.csv
Connecting to H2 database...
Creating tables in database...
Created table in given database...
Row Count: 197
.........................................................
... LOAD DATA FINISH .................................
.........................................................
...
----

== Testando
O método HTTP OPTIONS retorna cabeçalhos de controle de acesso na resposta, permitindo o compartilhamento de recursos de origem cruzada.

[source,json]
----
curl -i -X OPTIONS http://localhost:8080/greetings
----

[source,json]
----
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Max-Age: 3600
Access-Control-Allow-Headers: x-requested-with
X-Application-Context: application
Allow: GET, HEAD, POST, PUT, DELETE, TRACE, OPTIONS, PATCH
Content-Length: 0
Date: Fri, 05 Oct 2018 16:23:20 GMT
----